---
title: "STV @ District Health Boards"
---

There were 18 STV elections for district health boards around the country in 2019;
all except Waikato.


## Auckland District Health Board

Seven seats elected from 27 candidates in 35 iterations.

<iframe src="https://player.vimeo.com/video/375324697" width="640" height="896" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Bay of Plenty District Health Board

Seven seats elected from 21 candidates in 21 iterations.

<iframe src="https://player.vimeo.com/video/375324859" width="640" height="743" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Canterbury District Health Board

Seven seats elected from 23 candidates in 32 iterations.

<iframe src="https://player.vimeo.com/video/378978654" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Capital and Coast District Health Board

Seven seats elected from 23 candidates in 27 iterations.

<iframe src="https://player.vimeo.com/video/375325019" width="640" height="768" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>



## Counties Manukau District Health Board

Seven seats elected from 33 candidates in 49 iterations.

<iframe src="https://player.vimeo.com/video/375325038" width="640" height="1049" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Hawke's Bay District Health Board

Seven seats elected from 25 candidates in 30 iterations.

<iframe src="https://player.vimeo.com/video/378982813" width="640" height="846" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Hutt Valley District Health Board

Seven seats elected from 13 candidates in 28 iterations.

<iframe src="https://player.vimeo.com/video/374371592" width="640" height="536" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Lakes District Health Board

Seven seats elected from 17 candidates in 25 iterations.

<iframe src="https://player.vimeo.com/video/378980810" width="640" height="640" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## MidCentral District Health Board

Seven seats elected from 15 candidates in 12 iterations.

<iframe src="https://player.vimeo.com/video/373087886" width="640" height="588" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Nelson-Marlborough District Health Board

Seven seats elected from 14 candidates in 30 iterations.

<iframe src="https://player.vimeo.com/video/378980749" width="640" height="563" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Northland District Health Board

Seven seats elected from 20 candidates in 26 iterations.

<iframe src="https://player.vimeo.com/video/375361550" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## South Canterbury District Health Board

Seven seats elected from 13 candidates in 22 iterations.

<iframe src="https://player.vimeo.com/video/372589076" width="640" height="536" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Southern District Health Board, Otago Constituency

Four seats elected from 17 candidates in 19 iterations.

<iframe src="https://player.vimeo.com/video/378978710" width="640" height="640" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Southern District Health Board, Southland Constituency

Three seats elected from 11 candidates in nine iterations.

<iframe src="https://player.vimeo.com/video/378978730" width="640" height="486" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>



## Tairāwhiti District Health Board

Seven seats elected from 20 candidates in 28 iterations.

<iframe src="https://player.vimeo.com/video/375361237" width="640" height="716" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Taranaki District Health Board

Seven seats elected from 17 candidates in 18 iterations.

<iframe src="https://player.vimeo.com/video/375361295" width="640" height="640" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Wairarapa District Health Board

Seven seats elected from 10 candidates in 17 iterations.

<iframe src="https://player.vimeo.com/video/378980721" width="640" height="461" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Waitemata District Health Board

Seven seats elected from 23 candidates in 40 iterations.

<iframe src="https://player.vimeo.com/video/375361041" width="640" height="795" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## West Coast District Health Board

Seven seats elected from 15 candidates in 20 iterations.

<iframe src="https://player.vimeo.com/video/378980678" width="640" height="588" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Whanganui District Health Board

Seven seats elected from 17 candidates in 29 iterations.

<iframe src="https://player.vimeo.com/video/375360883" width="640" height="640" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>



## Data

XML (one file) supplied by Election Services on request;
XML (two files) supplied eventually by Electionz on request;
DOCX and XLSX supplied by local council on request;
PDF from board website;
TSVs manually extracted from DOCX/PDF.

* [adhb.xml](sources/2019/adhb.xml)
* [bopdhb.xml](sources/2019/bopdhb.xml)
* [cdhb.xml](sources/2019/cdhb.xml)
* [cdhb_names.xm](sources/2019/cdhb_names.xml)
* [cchb.xml](sources/2019/cchb.xml)
* [cchb_names.xm](sources/2019/cchb_names.xml)
* [ccdhb.pdf](sources/2019/ccdhb.pdf)
* [ccdhb_results.tsv](sources/2019/ccdhb_results.tsv)
* [ccdhb_iterations.tsv](sources/2019/ccdhb_iterations.tsv)
* [cmdhb.xml](sources/2019/cmdhb.xml)
* [hbdhb.xml](sources/2019/hbdhb.xml)
* [hbdhb_names.xm](sources/2019/hbdhb_names.xml)
* [hvdhb.xml](sources/2019/hvdhb.xml)
* [hvdhb_names.xm](sources/2019/hvdhb_names.xml)
* [hvdhb.docx](sources/2019/hvdhb.docx)
* [hvdhb_iterations.tsv](sources/2019/hvdhb_iterations.tsv)
* [hvdhb_results.tsv](sources/2019/hvdhb_results.tsv)
* [ldhb.xml](sources/2019/ldhb.xml)
* [ldhb_names.xm](sources/2019/ldhb_names.xml)
* [mcdhb.xml](sources/2019/mcdhb.xml)
* [mcdhb_names.xm](sources/2019/mcdhb_names.xml)
* [mcdhb.pdf](sources/2019/mcdhb.pdf)
* [mcdhb_results.tsv](sources/2019/mcdhb_results.tsv)
* [mcdhb_iterations.tsv](sources/2019/mcdhb_iterations.tsv)
* [ndhb.xml](sources/2019/ndhb.xml)
* [nmdhb.xml](sources/2019/nmdhb.xml)
* [nmdhb_names.xm](sources/2019/nmdhb_names.xml)
* [sdhb_otago.xml](sources/2019/sdhb_otago.xml)
* [sdhb_otago_names.xm](sources/2019/sdhb_otago_names.xml)
* [sdhb_southland.xml](sources/2019/sdhb_southland.xml)
* [sdhb_southland_names.xm](sources/2019/sdhb_southland_names.xml)
* [scdhb.xml](sources/2019/scdhb.xml)
* [scdhb_names.xm](sources/2019/scdhb_names.xml)
* [scdhb.pdf](sources/2019/scdhb.pdf)
* [scdhb_iterations.tsv](sources/2019/scdhb_iterations.tsv)
* [scdhb_results.tsv](sources/2019/scdhb_results.tsv)
* [taidhb.xml](sources/2019/taidhb.xml)
* [tardhb.xml](sources/2019/tardhb.xml)
* [wair-dhb.xml](sources/2019/wair-dhb.xml)
* [wair-dhb_names.xm](sources/2019/wair-dhb_names.xml)
* [wait-dhb.xml](sources/2019/wait-dhb.xml)
* [wcdhb.xml](sources/2019/wcdhb.xml)
* [wcdhb_names.xm](sources/2019/wcdhb_names.xml)
* [whan-dhb.xlsx](sources/2019/whan-dhb.xlsx)



