---
title: "STV @ Greater Wellington Regional Council"
---

There were six STV elections for Greater Wellington Regional Council in 2019.


## Kāpiti Coast Constituency

One seat elected from two candidates in one iteration.

<iframe src="https://player.vimeo.com/video/374370082" width="640" height="256" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Lower Hutt Constituency

Three seats elected from six candidates in five iterations.

<iframe src="https://player.vimeo.com/video/374370623" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Porirua-Tawa Constituency

Two seats elected from seven candidates in six iterations.

<iframe src="https://player.vimeo.com/video/374373703" width="640" height="384" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Upper Hutt Constituency

One seat elected from four candidates in three iterations.

<iframe src="https://player.vimeo.com/video/374373873" width="640" height="308" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Wairarapa Constituency

One seat elected from three candidates in two iterations.

<iframe src="https://player.vimeo.com/video/374373928" width="640" height="282" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Wellington Constituency

Five seats elected from 23 candidates in 29 iterations.

<iframe src="https://player.vimeo.com/video/374371069" width="640" height="793" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Data

PDF files downloaded from council website;
TSVs manually extracted using tabulizer.

* [gw_kapiti-coast.pdf](sources/2019/gw_kapiti-coast.pdf)
* [gw_kapiti-coast_iterations.tsv](sources/2019/gw_kapiti-coast_iterations.tsv)
* [gw_kapiti-coast_results.tsv](sources/2019/gw_kapiti-coast_results.tsv)
* [gw_lower-hutt.pdf](sources/2019/gw_lower-hutt.pdf)
* [gw_lower-hutt_iterations.tsv](sources/2019/gw_lower-hutt_iterations.tsv)
* [gw_lower-hutt_results.tsv](sources/2019/gw_lower-hutt_results.tsv)
* [gw_porirua-tawa.pdf](sources/2019/gw_porirua-tawa.pdf)
* [gw_porirua-tawa_iterations.tsv](sources/2019/gw_porirua-tawa_iterations.tsv)
* [gw_porirua-tawa_results.tsv](sources/2019/gw_porirua-tawa_results.tsv)
* [gw_upper-hutt.pdf](sources/2019/gw_upper-hutt.pdf)
* [gw_upper-hutt_iterations.tsv](sources/2019/gw_upper-hutt_iterations.tsv)
* [gw_upper-hutt_results.tsv](sources/2019/gw_upper-hutt_results.tsv)
* [gw_wairarapa.pdf](sources/2019/gw_wairarapa.pdf)
* [gw_wairarapa_iterations.tsv](sources/2019/gw_wairarapa_iterations.tsv)
* [gw_wairarapa_results.tsv](sources/2019/gw_wairarapa_results.tsv)
* [gw_wellington.pdf](sources/2019/gw_wellington.pdf)
* [gw_wellington_iterations.tsv](sources/2019/gw_wellington_iterations.tsv)
* [gw_wellington_results.tsv](sources/2019/gw_wellington_results.tsv)

