---
title: "STV @ Kāpiti Coast District Council"
---

There were nine STV elections for Kāpiti Coast District Council in 2019.

## Mayor

One seat elected from four candidates in three iterations.

<iframe src="https://player.vimeo.com/video/374047055" width="640" height="307" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Districtwide

Five seats elected from 14 candidates in 17 iterations.

<iframe src="https://player.vimeo.com/video/374047024" width="640" height="563" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Ōtaki Ward

One seat elected from three candidates in one iteration.

<iframe src="https://player.vimeo.com/video/374047078" width="640" height="282" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Paekākāriki-Raumati Ward

One seat elected from three candidates in one iteration.

<iframe src="https://player.vimeo.com/video/374047141" width="640" height="282" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Paraparaumu Ward

Two seats elected from four candidates in three iterations.

<iframe src="https://player.vimeo.com/video/374047157" width="640" height="308" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Waikanae Ward

One seat elected from three candidates in two iterations.

<iframe src="https://player.vimeo.com/video/374047173" width="640" height="282" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Ōtaki Community Board

Four seats elected from six candidates in four iterations.

<iframe src="https://player.vimeo.com/video/374047094" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Paekākāriki Community Board

Four seats elected from five candidates in three iterations.

<iframe src="https://player.vimeo.com/video/374047123" width="640" height="334" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Waikanae Community Board

Four seats elected from six candidates in five iterations.

<iframe src="https://player.vimeo.com/video/374047197" width="640" height="384" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>



## Data

Excel files downloaded from council website.

* [kcdc_mayor.xlsx](sources/2019/kcdc_mayor.xlsx)
* [kcdc_districtwide.xlsx](sources/2019/kcdc_districtwide.xlsx)
* [kcdc_otaki-ward.xlsx](sources/2019/kcdc_otaki-ward.xlsx)
* [kcdc_paekakariki-raumati-ward.xlsx](sources/2019/kcdc_paekakariki-raumati-ward.xlsx)
* [kcdc_paraparaumu-ward.xlsx](sources/2019/kcdc_paraparaumu-ward.xlsx)
* [kcdc_waikanae-ward.xlsx](sources/2019/kcdc_waikanae-ward.xlsx)
* [kcdc_otaki-community-board.xlsx](sources/2019/kcdc_otaki-community-board.xlsx)
* [kcdc_paekakariki-community-board.xlsx](sources/2019/kcdc_paekakariki-community-board.xlsx)
* [kcdc_waikanae-community-board.xlsx](sources/2019/kcdc_waikanae-community-board.xlsx)

