---
title: "STV @ Ruapehu District Council"
---

There were four STV elections for Ruapehu District Council in 2019.

## Mayor

One seat elected from two candidates in one iteration.

<iframe src="https://player.vimeo.com/video/374048850" width="640" height="564" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## National Park Ward

One seat elected from three candidates in two iterations.

<iframe src="https://player.vimeo.com/video/374048874" width="640" height="564" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Taumarunui Ward

Five seats elected from seven candidates in four iterations.

<iframe src="https://player.vimeo.com/video/374048887" width="640" height="564" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Waimarino-Waiouru Ward

Four seats elected from eight candidates in 11 iterations.

<iframe src="https://player.vimeo.com/video/374048907" width="640" height="564" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>



## Data

PDF file downloaded from council website;
TSVs manually extracted using tabulizer.

* [rdc.pdf](sources/2019/rdc.pdf)
* [rdc_mayor_iterations.tsv](sources/2019/rdc_mayor_iterations.tsv)
* [rdc_mayor_results.tsv](sources/2019/rdc_mayor_results.tsv)
* [rdc_national-park-ward_iterations.tsv](sources/2019/rdc_national-park-ward_iterations.tsv)
* [rdc_national-park-ward_results.tsv](sources/2019/rdc_national-park-ward_results.tsv)
* [rdc_taumarunui-ward_iterations.tsv](sources/2019/rdc_taumarunui-ward_iterations.tsv)
* [rdc_taumarunui-ward_results.tsv](sources/2019/rdc_taumarunui-ward_results.tsv)
* [rdc_waimarino-waiouru-ward_iterations.tsv](sources/2019/rdc_waimarino-waiouru-ward_iterations.tsv)
* [rdc_waimarino-waiouru-ward_results.tsv](sources/2019/rdc_waimarino-waiouru-ward_results.tsv)

