---
title: "STV @ Tauranga City Council"
---

There were five STV elections for Tauranga Council in 2019.

## Mayor

One seat elected from 10 candidates in nine iterations.

<iframe src="https://player.vimeo.com/video/373032822" width="640" height="461" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## At Large

Four seats elected from 19 candidates in 21 iterations.

<iframe src="https://player.vimeo.com/video/373032657" width="640" height="692" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Mount Maunganui-Papamoa Ward

Two seats elected from seven candidates in five iterations.

<iframe src="https://player.vimeo.com/video/373032880" width="640" height="384" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Otumoetai-Pyes Pa Ward

Two seats elected from seven candidates in five iterations.

<iframe src="https://player.vimeo.com/video/373032920" width="640" height="384" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Te Papa-Welcome Bay Ward

Two seats elected from ten candidates in ten iterations.

<iframe src="https://player.vimeo.com/video/373032990" width="640" height="461" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>


## Data

Original PDF from council website. TSVs extracted using tabulizer.

* [tcc.pdf](sources/2019/tcc.pdf)
* [tcc_mayor_results.tsv](sources/2019/tcc_mayor_results.tsv)
* [tcc_mayor_iterations.tsv](sources/2019/tcc_mayor_iterations.tsv)
* [tcc_at-large_results.tsv](sources/2019/tcc_at-large_results.tsv)
* [tcc_at-large_iterations.tsv](sources/2019/tcc_at-large_iterations.tsv)
* [tcc_mount-maunganui-papamoa_results.tsv](sources/2019/tcc_mount-maunganui-papamoa_results.tsv)
* [tcc_mount-maunganui-papamoa_iterations.tsv](sources/2019/tcc_mount-maunganui-papamoa_iterations.tsv)
* [tcc_otumoetai-pyes-pa_results.tsv](sources/2019/tcc_otumoetai-pyes-pa_results.tsv)
* [tcc_otumoetai-pyes-pa_iterations.tsv](sources/2019/tcc_otumoetai-pyes-pa_iterations.tsv)
* [tcc_te-papa-welcome-bay_results.tsv](sources/2019/tcc_te-papa-welcome-bay_results.tsv)
* [tcc_te-papa-welcome-bay_iterations.tsv](sources/2019/tcc_te-papa-welcome-bay_iterations.tsv)

